# Mandatory settings

name: BLOGHICN
paginate: 15
url: https://www.bloghicn.ga
enforce_ssl: www.bloghicn.ga
markdown: kramdown
blog_theme: light # Or use dark

# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: bloghicn
ga_analytics: UA-84821720-4
google_site_verification: kS2M5Iee7pnljyuRn_BLDiVSwguipxVCBAbzVcnJv2g
local_fonts: true # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: habibimroncn
  flickr: # Add your Flickr handle
  github: habibimroncn
  linkedin: habib-nugroho-689410ab
  twitter: Hab_15
  email: habibimron1508@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: true
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
footer_link:
  my_self_link: http://habibimroncn.github.io
  other_link: http://habibimroncn.github.io
firebase:
  firebase_asset: true