---
title: BLOGHICN
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: "Blog yang berisikan catatan dari seorang kuli. \n"
permalink: posts/:title/
baseurl: 
url: https://www.bloghicn.ga
enforce_ssl: www.bloghicn.ga
author: Habib Imron Cahyo Nugroho
author-img: habib-imron-cahyo-nugroho.jpg
about-author: Hanya seorang kuli.
twitter: Hab_15
facebook: habibimroncn
github: habibimroncn
linkedin: habib-nugroho
email: habibimron1508@gmail.com
discus-identifier: bloghicn
analytics: UA-84821720-4
markdown: kramdown
plugins:
- jekyll-sitemap
- jemoji
- jekyll-admin
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
visual-cv-url: https://www.visualcv.com/habibimroncn
